config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
      }
  root to: 'pages#home'

  get 'users/:id', to: 'users#show', as: :user
  get 'restaurants/:id/meetings', to: 'restaurants#meetings', as: 'available_meetings'
  get 'users/:id/reviews', to: 'reviews#new', as: 'user_review'
  post 'users/:id/reviews', to: 'reviews#create'
  # get 'restaurants/map', to: 'restaurants#map'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create]
  resources :meetings, only: [:index, :show, :create, :new, :destroy]
  resources :guests
  resources :reviews, only: [:new, :create]
  resources :chat_rooms, only: [ :show , :index] do
    resources :messages, only: [ :create ]
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_many :guests, dependent: :destroy
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def index
    @meetings = Meeting.where(user: current_user)
    @user_guest = Guest.where(user: current_user)
    @any_created_or_booked = @meetings + @user_guest

  end

  def show
    @meeting = Meeting.find(params[:id])
    @guests = Guest.all
    @marker = [{
      lat: @meeting.restaurant.latitude,
      lng: @meeting.restaurant.longitude,
      image_url: helpers.asset_url('green-pin.png'),
      infoWindow: render_to_string(partial: "info_window", locals: { restaurant: @meeting.restaurant})
    }]
  end


  def create
    @meeting = Meeting.new(meeting_params)
    if @meeting.save!
      redirect_to meeting_path(@meeting)
    # else
    #   render 'new'
    end
  end

  def update
    @meeting = Meeting.find(params[:id])
    respond_to do
      if @meeting.update meeting_params
      end
    end
  end

  def destroy
      @meeting = Meeting.find(params[:id])
      @meeting.destroy
      redirect_to meetings_path
  end

  private

  def meeting_params
    params.require(:meeting).permit(:restaurant_id, :user_id, :meet_time)
  end
end

app/views/meetings/_info_window.html.erb
<div class='d-flex flex-column align-items-center info-window'>
  <h3><%= restaurant.name %></h3>
  <p><%= restaurant.address %></p>
</div>

app/views/meetings/index.html.erb
<div class='d-flex flex-column align-items-center'>
  <% if @any_created_or_booked == [] %>
    <div class='d-flex text-center'>
      <h2 class='oh-no'>No hosted meals!</h2>
    </div>
  <% else %>
    <h1 class="meeting-exterior-text">My hosted meals</h1>
      <div class='cards'>
        <% if @meetings == [] %>
          <h3 class='meeting-exterior-text px-3'>You're not a host of any meals</h3>
        <% else %>
          <div class="cards-container d-flex flex-wrap align-items-center justify-content-center">
            <% @meetings.each do |meeting| %>
              <div class = 'card-meeting p-3 my-1'>
                <div class="card-meeting-text">
                  <h2 class= 'card-meeting-title center-text'><%= meeting.restaurant.name %></h2>
                    <p><%= meeting.restaurant.address %></p>
                    <h3 class="card-meeting-title"><%= meeting.meet_time.strftime("%H:%M")%></h3>
                    <% if meeting.created_at.to_date == Date.today %>
                      <h3 class="card-meeting-title">Today</h3>
                    <% else %>
                      <p><%= meeting.created_at.strftime("%d-%m-%Y") %></p>
                    <% end %>
                </div>

                <div class='d-flex align-items-center flex-column'>
                  <%= link_to 'Show Details', meeting_path(meeting), class: 'btn-thin btn-orange' %>
                  <% if Guest.where(meeting: meeting.id) != [] %>
                    <h3 class='purple'>Your guest is:</h3>
                    <%= link_to Guest.find_by(meeting: meeting.id).user.first_name, user_path(Guest.find_by(meeting: meeting.id).user) %>
                    <%= link_to 'Chat', chat_room_path(ChatRoom.find_by(guest: Guest.find_by(meeting: meeting.id).id).id), class: 'btn-thin btn-orange' %>
                  <% end %>
                  <%= link_to 'Restaurant Details', restaurant_path(meeting.restaurant), class: 'btn-thin btn-orange' %>
                  <%= link_to 'Cancel', meeting_path(meeting), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn-thin btn-cancel' %>
                </div>
              </div>
            <% end %>
          </div>

        <% end %>

    <h1 class="meeting-exterior-text">Joined meals</h1>
      <% if @user_guest == [] %>
          <h3 class="meeting-exterior-text">No meals joined</h3>
      <% else %>
        <div class="cards-container d-flex flex-wrap align-items-center justify-content-center">
          <% @user_guest.each do |guest| %>
            <div class = 'card-meeting p-3 my-1'>
              <div class="card-meeting-text">
                <h2 class= 'card-meeting-title'><%= guest.meeting.restaurant.name %></h2>
                <p><%= guest.meeting.restaurant.address %></p>
                <p><%= guest.meeting.meet_time.strftime("%H:%M")%></p>
                <h3>Hosted by:</h3>
                <%= link_to guest.meeting.user.first_name, user_path(guest.meeting.user) %>
                <%= link_to cl_image_tag(guest.meeting.user.photo), user_path(guest.meeting.user), class: "avatar-link-large" %>
              </div>
              <div id='fake-notification'></div>
              <div class='d-flex align-items-center flex-column'>
                <%= link_to 'Show Details', meeting_path(guest.meeting), class: 'btn-thin btn-orange' %>
                <%=  %>
                <%= link_to 'Chat', chat_room_path(ChatRoom.find_by(guest: guest)), class: 'btn-thin btn-orange' %>
                <%= link_to 'Restaurant Details', restaurant_path(guest.meeting.restaurant), class: 'btn-thin btn-orange' %>
                <%= link_to 'Cancel', guest_path(guest), method: :delete, data: { confirm: "Are you sure? you're losing a chance to meet your potential new bestie" }, class: 'btn-thin btn-cancel' %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <br>

    <div>
      <%= link_to 'View restaurants', restaurants_path, class: 'btn-thin btn-orange' %>
    </div>
</div>

app/views/meetings/show.html.erb
<title>Mango - Not having a companion to eat with when out. </title>

<div class='d-flex flex-column align-items-center'>
  <div class="card-restaurant-info">
    <h1><%= @meeting.restaurant.name %></h1>
    <p><%= @meeting.restaurant.address %></p>
  </div>
  <div class="member-card-info">
    <%= link_to cl_image_tag(@meeting.user.photo), user_path(@meeting.user), class: "profile-picture" %>
    <div class="member-details" >
    <h2><%= @meeting.user.first_name %></h2>
    <p><%= @meeting.user.interest %></p>
    </div>
  </div>
  <div class="member-card-info">
    <% @meeting.guests.each do |guest| %>
      <%= link_to user_path(guest.user_id), class: "member-link" do %>
      <div class="profile-picture">
        <%= cl_image_tag(User.find(guest.user_id).photo, crop: :fill) %>
      </div>
      <div class="member-details">
        <h2><%= User.find(guest.user_id).first_name %></h2>
        <p><%= User.find(guest.user_id).interest %></p>
        </div>
      <% end %>
    <% end %>
  </div>

   <div>
    <% if Guest.where(meeting: @meeting) == [] && @meeting.user != current_user %>
      <%= simple_form_for Guest.new do |f| %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :meeting_id, :value => params[:id] %>
        <%#= f.hidden_field :meet_time, :value => Date.today %>
        <%= f.submit 'Join meal', class: 'btn-thin btn-orange' %>
      <% end %>
    <% end %>
  </div>
    <div
    id="map"
    style="width: 100%;
    height: 400px;"
    data-markers="<%= @marker.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>


  <div class="btn-create-meeting my-3">
    <%= link_to 'My meals', meetings_path, class: 'btn-thin btn-orange' %>
  </div>
</div>
<%# raise %>