config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
      }
  root to: 'pages#home'

  get 'users/:id', to: 'users#show', as: :user
  get 'restaurants/:id/meetings', to: 'restaurants#meetings', as: 'available_meetings'
  get 'users/:id/reviews', to: 'reviews#new', as: 'user_review'
  post 'users/:id/reviews', to: 'reviews#create'
  # get 'restaurants/map', to: 'restaurants#map'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create]
  resources :meetings, only: [:index, :show, :create, :new, :destroy]
  resources :guests
  resources :reviews, only: [:new, :create]
  resources :chat_rooms, only: [ :show , :index] do
    resources :messages, only: [ :create ]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :meetings
  has_many :messages, dependent: :destroy
  has_many :reviews, dependent: :destroy
  mount_uploader :photo, PhotoUploader
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def after_update_path_for(resource)
    user_path(resource)
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    total_rating = 0
    @user = User.find(params[:id])

    if Review.where(user: @user).count > 0
      @ratings = Review.where(user: @user).each do |review|
        total_rating += review.rating
      end
      @average_rating = total_rating / Review.where(user: @user).count
    end

    @reviews = Review.where(user: @user)
  end

  # def update
  #   @user = User.find(params[:id])
  #   @user.update(user_params)
  # end

  private
  # def user_params
  #   params.require(:user).permit(:first_name, :last_name, :interest, :photo)
  # end
end

app/views/users/show.html.erb
<title>Mango - Profile page: Not having a companion to eat with when out. </title>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="profile-container">
  <div class="profile-pic">
  <%= cl_image_tag @user.photo, alt: "profile-pic", class: "card-avatar" %>
    <div class="profile-pic-info">
      <h1><%= @user.first_name %></h1>
      <div class="profile-pic-rating">
        <% if @average_rating %>
          <% @average_rating.times do |i| %>
            <i class="fas fa-star"></i>
          <% end %>
        <% else %>
          <h4>No ratings </h4>
        <% end %>
        <%= @reviews.count %>
      </div>
    </div>
  </div>
  <% if @user != current_user %>
    <%= link_to 'Leave a review', user_review_path(@user) %>
  <% end %>

  <div class="information-card">

    <div class="interests-card my-3">
      <div class="card-title-edit">
        <h2>Interests</h2>
        <% if @user == current_user %>
          <%= link_to edit_user_registration_path do %>
          <i class="far fa-edit"></i>
          <% end %>
        <% end %>
      </div>
      <p class="card-meeting-title"><%= @user.interest %></p>
    </div>

      <div class="interests-card my-3">
        <div class="card-title-edit">
          <h2>Food preferences</h2>
          <% if @user == current_user %>
            <%= link_to edit_user_registration_path do %>
              <i class="far fa-edit"></i>
            <% end %>
          <% end %>
        </div>
        <p class="card-meeting-title"><%= @user.food_preferences %></p>
      </div>

      <!-- <div class="interests-card">
        <div class="card-title-edit">
          <h2>Food allergies and intolerances</h2>
          <% if @user == current_user %>
            <%= link_to edit_user_registration_path do %>
              <i class="far fa-edit"></i>
            <% end %> -->
        <% end %>
      </div>
    </div>
  </div>
</div>