config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
      }
  root to: 'pages#home'

  get 'users/:id', to: 'users#show', as: :user
  get 'restaurants/:id/meetings', to: 'restaurants#meetings', as: 'available_meetings'
  get 'users/:id/reviews', to: 'reviews#new', as: 'user_review'
  post 'users/:id/reviews', to: 'reviews#create'
  # get 'restaurants/map', to: 'restaurants#map'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create]
  resources :meetings, only: [:index, :show, :create, :new, :destroy]
  resources :guests
  resources :reviews, only: [:new, :create]
  resources :chat_rooms, only: [ :show , :index] do
    resources :messages, only: [ :create ]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">


  <div class="footer-links">

    <%= link_to'<button><i class="far fa-calendar-check" aria-hidden="true" icon></i></button>'.html_safe,meetings_path %>

    <%= link_to'<button><i class="far fa-comments" aria-hidden="true"></i></button>'.html_safe,chat_rooms_path %>

    <%= link_to '<button type="button"> <i class="fas fa-search" aria-hidden="true" icon></i></button>'.html_safe, restaurants_path %>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">


    <%#= image_tag "mango_logo.jpg", alt: "Logo", class: "navbar-brand" %>
    <%= link_to user_path(current_user.id) do %>
    <%= cl_image_tag current_user.photo, class: "avatar" %>
    <% end %>
  <p class="navtitle">Mango</p>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-link active">
          <%= link_to "Home", restaurants_path, class: "nav-link" %>
        </li>
        <li class="nav-link"> <%= link_to "Profile", user_path(current_user.id), class: "nav-link" %>

        <li class="nav-link"> <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>