config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
      }
  root to: 'pages#home'

  get 'users/:id', to: 'users#show', as: :user
  get 'restaurants/:id/meetings', to: 'restaurants#meetings', as: 'available_meetings'
  get 'users/:id/reviews', to: 'reviews#new', as: 'user_review'
  post 'users/:id/reviews', to: 'reviews#create'
  # get 'restaurants/map', to: 'restaurants#map'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create]
  resources :meetings, only: [:index, :show, :create, :new, :destroy]
  resources :guests
  resources :reviews, only: [:new, :create]
  resources :chat_rooms, only: [ :show , :index] do
    resources :messages, only: [ :create ]
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :meetings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.geocoded.order(created_at: :desc)
    @meetingPlaces = Restaurant.joins(:meetings).uniq

    @markers = @restaurants.map do |restaurant|
      if @meetingPlaces.include?(restaurant)
          img = helpers.asset_url('green-pin.png')
          meetings_available = true
          own_meeting = own_meeting_check(restaurant)
        else
          img = helpers.asset_url('pink-map-pin.png')
          meetings_available = false
          own_meeting = false
      end

      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        image_url: helpers.asset_url(img),
        infoWindow: render_to_string(partial: "info_window", locals: { restaurant: restaurant, meetings_available: meetings_available, own_meeting: own_meeting })
      }

    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path(new: true)
    else
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @has_meeting = Restaurant.joins(:meetings).uniq.include?(@restaurant)
  end

  def meetings
    @restaurant = Restaurant.find(params[:id])
    @meetings = Meeting.where(restaurant: @restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :photo)
  end

  def own_meeting_check(restaurant)
    @user_meetings = Meeting.where(user: current_user)
    @user_guest = Guest.where(user: current_user)

    found = false
    @user_meetings.each do |meeting|
      if meeting.restaurant == restaurant
        found = true
      end
    end
    @user_guest.each do |is_guest|
      if is_guest.meeting.restaurant == restaurant
        found = true
      end
    end
    return found
  end

end

app/views/restaurants/_info_window.html.erb
<title>Mango - Not having a companion to eat with when out. </title>

<div class='d-flex flex-column info-window text-center'>
  <h3><%= restaurant.name %></h3>
  <p><%= restaurant.address %></p>
  <%= image_tag restaurant.photo %>
  <% if meetings_available %>
    <% if own_meeting %>
      <h4><%= link_to "Join a meal", meetings_path, class: "btn-thin btn-orange my-1"%></h4>
    <% elsif %>
      <%= link_to "Join a meal", available_meetings_path(restaurant), class: "btn-thin btn-orange my-1"%>
    <% end %>
  <% end %>
  <%= link_to "Arrange a meal", restaurant_path(restaurant), class: "btn-thin btn-orange my-1" %>
</div>

app/views/restaurants/_map.html.erb
<title>Mango - Not having a companion to eat with when out. </title>

<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/restaurants/index.html.erb
<title>Mango - Not having a companion to eat with when out. </title>

<div>
  <div class="title-card">
    <h1 class="title">Restaurants</h1>
  </div>
  <div class="d-flex justify-content-center">
    <ul class="nav nav-pills" id="banner-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="banner-map-tab" data-toggle="pill" href="#mapbox" role="tab" aria-controls="mapbox" aria-selected="true" onclick="return false">Map</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="banner-list-tab" data-toggle="pill" href="#list" role="tab" aria-controls="list" aria-selected="false" onclick="return false">List</a>
      </li>
    </ul>
  </div>
  <div class="tab-content">
    <div id="mapbox" class="tab-pane fade in active show ">
      <div id='map-button'>
        <%= render 'map' %>
      </div>
    </div>
    <div id="list" class="tab-pane fade">
      <div class="container-fluid">
        <div class="row justify-content-around">
          <% @restaurants.each do |restaurant| %>
            <div class="card-restaurant-wrap col-sm-10 col-md-6 col-lg-4 d-flex justify-content-center">
              <div class="card-restaurant">
                <%= image_tag restaurant.photo %>
                <p class='rest-distance p-1'><%= restaurant.distance_to([51.515696, -0.104113]).round(1)%> Miles</p>
                <div class="card-restaurant-text">
                  <h3 class="rest-title"><%= restaurant.name %></h3>
                  <% if @meetingPlaces.include?(restaurant) %>
                    <div class="btn-thin btn-green">
                      <%= link_to 'Join a meal', available_meetings_path(restaurant) %>
                    </div>
                    <div class="btn-orange btn-thin">
                      <%= link_to 'Arrange a meal', restaurant_path(restaurant) %>
                    </div>
                  <% else %><br>
                    <div class="btn-orange btn-thin">
                      <%= link_to 'Arrange a meal', restaurant_path(restaurant) %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/meetings.html.erb
<title>Mango - Not having a companion to eat with when out. </title>
<div class="container" >
    <div class='d-flex flex-column align-items-center'>
      <h1 class="meeting-exterior-text">Open meals to join at <%= @restaurant.name %></h1>
      <div class='cards'>
        <% @meetings.each do |meeting| %>
          <div class = 'card-meeting p-3 my-1'>
            <div class="card-meeting-text">
              <h3><%= meeting.user.first_name %></h3>
              <%= link_to cl_image_tag(meeting.user.photo), user_path(meeting.user), class: "avatar-link-large" %>
              <p><%= meeting.restaurant.address %></p>
              <p><%= meeting.meet_time.strftime("%H:%M")%></p>
            </div>

            <div class='d-flex align-items-center flex-column'>
              <%= link_to 'Show Details', meeting_path(meeting), class: 'btn-thin btn-orange' %>
            </div>
          </div>
        <% end %>
      </div>
      <%= link_to 'Back to map', restaurants_path, class: 'btn-thin btn-cancel' %>
    </div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for @restaurant do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :photo %>
        <%= f.submit "Add restaurant" %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<title>Mango - Not having a companion to eat with when out. </title>

<div class="card-1">
  <div class='d-flex flex-column align-items-center'>
    <!-- <div class="button-space"> -->
      <div class="card-product my-3">
        <%= image_tag @restaurant.photo %>
        <div class="card-product-infos">
          <div class="card-title">
            <h2><%= @restaurant.name  %></h2>
            <p><%= @restaurant.address %></p>
          </div>
         <%= simple_form_for Meeting.new do |f| %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.hidden_field :restaurant_id, :value => params[:id] %>
            <%#= f.hidden_field :meet_time, :value => Date.today %>
            <%= f.input :meet_time, as: :time %>
            <div class="center">
              <%= f.submit 'Arrange a meal', class: 'btn-thin btn-orange' %>

            </div>
          <% end %>
        </div>
      </div>
      <% if @has_meeting %>
      <div class="meeting-button">
        <%= link_to 'Join a meal', available_meetings_path(@restaurant), class: 'btn-thin btn-green' %>
      </div>
      <% end %>
      <%= link_to 'Back', restaurants_path, class: 'btn-thin btn-orange my-3' %>
    </div>

  <!-- </div> -->
</div>